version: '3.8'

services:
  cardcatalogapi:
    image: cardcatalogapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
    networks:
      - ccapi-network
    volumes:
      - /local/path/to/database/folder:/database

networks:
    ccapi-network:
        driver: bridge